In [16]:
#Q1
import numpy as np


def fact(num):
    if(num==0 or num==1):
        return 1
    return num*fact(num-1)
print('factotial is : ', fact(3))


def fib(n):
    if n==1 or n==2:
        return 1
    return fib(n-1)+fib(n-2)
for i in range(1,10):
    print(fib(i))
    
    
#Star
num=10
l=1
while(num<=l):
    print('*')
print()




factotial is :  6
1
1
2
3
5
8
13
21
34



In [11]:
#Q2
#Create 3D array in 10 ways:

import numpy as np

#1
a1=np.array([[[1,2],[3,4]],[[1,2],[3,4]]])
print('a1', a1)

#2
a2=np.arange(2,20).reshape(2,3,3)
print('a2 ',a2)

#3
a3= np.linspace(1,10,8).reshape(2,2,2)
print('a3 ',a3)

#4
a4=np.zeros((3,3,3))
print('a4 ',a4)

#5
a5=np.random.rand(2,2,2)
print('a5 ',a5)

#6


a1 [[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]
a2  [[[ 2  3  4]
  [ 5  6  7]
  [ 8  9 10]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]
a3  [[[ 1.          2.28571429]
  [ 3.57142857  4.85714286]]

 [[ 6.14285714  7.42857143]
  [ 8.71428571 10.        ]]]
a4  [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
a5  [[[0.87060443 0.11368173]
  [0.65117268 0.15543529]]

 [[0.83970013 0.92216495]
  [0.31427114 0.99711968]]]


In [ ]:
#Q3 Why numpy 2D and 3D arra is considered as object type for series creation ????????????

#Ans- Beause Set is not in unordered tye Data Structure, and it does not have any indentation, 
#... Series indices store objects, not their individual scalar components
# ... So, it's not possible to cnvert into the list as for the Pandas Library

In [12]:
#Q4
import numpy as np
import pandas as pd

tup = (1, 20, 3, 6)
dist = {'w': 1, 'x': 4, 'y': 6, 'z': 3}
s2 = pd.Series(tup)
print(s2)
s3 = pd.Series(dist)
print(s3)

0     1
1    20
2     3
3     6
dtype: int64
w    1
x    4
y    6
z    3
dtype: int64


In [6]:
#Q5
import numpy as np

# u = input("Enter elements ")
# el = u.split()
# array = np.array(el, dtype=int)

# print("The  array is:",array)



Enter elements 3 6 8
The  array is: [3 6 8]
