In [2]:
################# ML LAB ASSIGNMENT 1 ################

#Submited by : Debajyoti Bhakta
# Reg No. 2341002155 | Section: 23412G1 | Sl no. 09


In [6]:
#Q1. 
print("Enter Marks: ")
marks = int( input())
print(marks)

if(marks<=100):
    if(marks>=90):
        print('A')
    elif(marks>=75 and marks<=89):
        print('B')
    elif(marks>=50 and marks<=74):
        print('C')
    elif(marks<=50):
        print('Fail')
        
else:
    print('No result')

Enter Marks: 


 95


95
A


In [1]:
#Q2
print("Enter a Number")
n = int(input())   
total = 0

while n > 0:
    digit = n % 10      
    total += digit      
    n = n // 10         

print("Sum of digits:", total)


Enter a Number


 23


Sum of digits: 5


In [5]:
#Q3
def is_prime(n):
    if n <= 1:
        return False
    if n == 2:
        return True
    if n % 2 == 0:
        return False
    
        for i in range(3, int(n ** 0.5) + 1, 2):
            if n % i == 0:
                return False
        return True


test_values = [0, 1, 2, 3, 4, 5, 11, 16, 17, 19, 20, 23, 25, 29, 97, 100]

for val in test_values:
    print(f"{val} -> {is_prime(val)}")



0 -> False
1 -> False
2 -> True
3 -> None
4 -> False
5 -> None
11 -> None
16 -> False
17 -> None
19 -> None
20 -> False
23 -> None
25 -> None
29 -> None
97 -> None
100 -> False


In [7]:
#Q4
def is_palindrome(word):
    word = word.lower()
    return word == word[::-1]


test_words = ["madam"]

for w in test_words:
    if is_palindrome(w):
        print(f"{w} → Palindrome")
    else:
        print(f"{w} → Not Palindrome")


madam → Palindrome


In [9]:
#Q5
import numpy as np

A = np.array([
    [2,  1,  3],
    [1,  0,  2],
    [3,  4,  5]
], dtype=float)

B = np.array([
    [9,  8,  7],
    [6,  5,  4],
    [3,  2,  1]
], dtype=float)

# a) Matrix multiplication (A x B) 
product = A.dot(B)   # or np.matmul(A, B)

# b) Determinant of each matrix 
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)

# c) Inverse 
def compute_inverse_if_possible(M, name="Matrix"):
    det = np.linalg.det(M)
    if abs(det) < 1e-12:   
        print(f"{name} is singular (determinant ≈ 0). Inverse does NOT exist.")
        return None
    inv = np.linalg.inv(M)
    return inv

inv_A = compute_inverse_if_possible(A, "A")
inv_B = compute_inverse_if_possible(B, "B")

def verify_inverse(M, M_inv, name="Matrix"):
    if M_inv is None:
        print(f"Cannot verify inverse for {name} since inverse does not exist.")
        return
    I_approx = M.dot(M_inv)
    I_exact = np.eye(M.shape[0])
    is_identity = np.allclose(I_approx, I_exact, atol=1e-9)
    print(f"\nVerification for {name}:")
    print("M × M⁻¹ (approx):")
    print(np.round(I_approx, 10))  
    print("Is close to identity matrix?:", is_identity)

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

print("\n--- a) A × B (Matrix Multiplication) ---")
print(product)

print("\n--- b) Determinants ---")
print(f"det(A) = {det_A}")
print(f"det(B) = {det_B}")

print("\n--- c) Inverse(s) ---")
if inv_A is not None:
    print("\nInverse of A (A⁻¹):")
    print(inv_A)
else:
    print("\nA has no inverse.")

if inv_B is not None:
    print("\nInverse of B (B⁻¹):")
    print(inv_B)
else:
    print("\nB has no inverse.")

verify_inverse(A, inv_A, "A")
verify_inverse(B, inv_B, "B")


B is singular (determinant ≈ 0). Inverse does NOT exist.
Matrix A:
[[2. 1. 3.]
 [1. 0. 2.]
 [3. 4. 5.]]

Matrix B:
[[9. 8. 7.]
 [6. 5. 4.]
 [3. 2. 1.]]

--- a) A × B (Matrix Multiplication) ---
[[33. 27. 21.]
 [15. 12.  9.]
 [66. 54. 42.]]

--- b) Determinants ---
det(A) = -2.9999999999999996
det(B) = 6.66133814775094e-16

--- c) Inverse(s) ---

Inverse of A (A⁻¹):
[[ 2.66666667 -2.33333333 -0.66666667]
 [-0.33333333 -0.33333333  0.33333333]
 [-1.33333333  1.66666667  0.33333333]]

B has no inverse.

Verification for A:
M × M⁻¹ (approx):
[[ 1. -0. -0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]
Is close to identity matrix?: True
Cannot verify inverse for B since inverse does not exist.


In [10]:
#Q6
import numpy as np

arr1 = np.random.randint(1, 51, size=10)
arr2 = np.random.randint(1, 51, size=10)

print("Array 1:", arr1)
print("Array 2:", arr2)

greater = arr1 > arr2
less = arr1 < arr2
equal = arr1 == arr2

print("\nElement-wise comparison:")
print("arr1 > arr2:", greater)
print("arr1 < arr2:", less)
print("arr1 == arr2:", equal)

count_greater = np.sum(greater)
print("\nNumber of times arr1 > arr2:", count_greater)


Array 1: [22 10 47 26 18 50 29 13 50  5]
Array 2: [35 45 26 25  4 11 28 28 46 10]

Element-wise comparison:
arr1 > arr2: [False False  True  True  True  True  True False  True False]
arr1 < arr2: [ True  True False False False False False  True False  True]
arr1 == arr2: [False False False False False False False False False False]

Number of times arr1 > arr2: 6


In [12]:
#Q7
import numpy as np

marks_list = [45, 78, 88, 56, 92, 67, 81, 73, 59, 90]
marks = np.array(marks_list)
print("Marks of students:", marks)

# a) Average marks of the class
average = np.mean(marks)
print("\nAverage marks of the class:", average)

# b) Students who scored above average
above_avg = marks[marks > average]
print("\nStudents who scored above average:", above_avg)


Marks of students: [45 78 88 56 92 67 81 73 59 90]

Average marks of the class: 72.9

Students who scored above average: [78 88 92 81 73 90]


In [13]:
# Q8
import numpy as np

arr = np.arange(1, 17).reshape(4, 4)
print("4×4 Array:\n", arr)

# a) Extract the second row
second_row = arr[1, :]  
print("\nSecond row:", second_row)

# b) Extract the third column
third_col = arr[:, 2]   
print("\nThird column:", third_col)

# c) Slice the sub-matrix (2×2) from the bottom-right corner
sub_matrix = arr[2:4, 2:4]  
print("\n2×2 Sub-matrix from bottom-right corner:\n", sub_matrix)


4×4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Second row: [5 6 7 8]

Third column: [ 3  7 11 15]

2×2 Sub-matrix from bottom-right corner:
 [[11 12]
 [15 16]]


In [14]:
#Q9
import numpy as np
arr = np.arange(1, 13).reshape(3, 4)

print("Original 3×4 Array:\n", arr)

reshaped = arr.reshape(4, 3)
print("\nReshaped Array (4×3):\n", reshaped)

ravelled = arr.ravel()
print("\nRavelled Array (1D):\n", ravelled)

reshaped[0, 0] = 100
print("\nAfter modifying reshaped[0,0] = 100")
print("Original Array:\n", arr)      
print("Reshaped Array:\n", reshaped)

ravelled[0] = 999
print("\nAfter modifying ravelled[0] = 999")
print("Original Array:\n", arr)     
print("Ravelled Array:\n", ravelled)


Original 3×4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped Array (4×3):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Ravelled Array (1D):
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

After modifying reshaped[0,0] = 100
Original Array:
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Reshaped Array:
 [[100   2   3]
 [  4   5   6]
 [  7   8   9]
 [ 10  11  12]]

After modifying ravelled[0] = 999
Original Array:
 [[999   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Ravelled Array:
 [999   2   3   4   5   6   7   8   9  10  11  12]


In [15]:
# Q10
import numpy as np

rolls = np.random.randint(1, 7, size=1000)  
unique, counts = np.unique(rolls, return_counts=True)  
frequency = dict(zip(unique, counts))

print("Dice Roll Frequencies (Face: Count):")
print(frequency)


Dice Roll Frequencies (Face: Count):
{1: 163, 2: 160, 3: 197, 4: 159, 5: 153, 6: 168}
