In [10]:
#Q4 

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

data = pd.read_csv('btissue(1).csv')
X = data.iloc[:, :-1]
Y = data.iloc[:, -1]  

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.5, random_state=100)

rf = RandomForestClassifier(random_state=123)
rf.fit(X_train, Y_train)

Y_pred = rf.predict(X_test)

print("Accurecy score:\n ",accuracy_score(Y_test, Y_pred))
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))


Accurecy score:
  0.660377358490566
Confusion Matrix:
 [[12  0  0  0  0  0]
 [ 0  6  0  0  0  1]
 [ 3  0  6  0  0  1]
 [ 0  0  0  3  5  2]
 [ 0  0  0  0  5  1]
 [ 0  1  0  1  3  3]]


In [12]:
#Q5

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score 

data = pd.read_csv('auto_mpg.csv')
data = data.dropna(axis=0, how='any')

X = data.iloc[:, 1:8]
Y = data.iloc[:, 0]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.5, random_state=100)
model = LinearRegression().fit(X_train, Y_train)
Y_pred = model.predict(X_test)

print(mean_squared_error(Y_test, Y_pred))
print(r2_score(Y_test, Y_pred))


11.288925521020799
0.7965676976561301


In [7]:
#Q6

import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.metrics.cluster import v_measure_score
from sklearn.metrics import silhouette_score

data = pd.read_csv("Dataset_spine.csv")
data_1 = data.iloc[:, :11]
print(data_1)
data_2 = data.iloc[:, 12]

kmeans = KMeans(n_clusters=3, random_state=123, n_init=1)
kmeans.fit(data_1)
cluster_label = kmeans.predict(data_1)

v = v_measure_score(data_2, cluster_label)  
s = silhouette_score(data_1, cluster_label, metric='euclidean', sample_size=len(data_1))

print(v)
print(s)


          Col1       Col2       Col3       Col4        Col5       Col6  \
0    63.027817  22.552586  39.609117  40.475232   98.672917  -0.254400   
1    39.056951  10.060991  25.015378  28.995960  114.405425   4.564259   
2    68.832021  22.218482  50.092194  46.613539  105.985135  -3.530317   
3    69.297008  24.652878  44.311238  44.644130  101.868495  11.211523   
4    49.712859   9.652075  28.317406  40.060784  108.168725   7.918501   
..         ...        ...        ...        ...         ...        ...   
305  47.903565  13.616688  36.000000  34.286877  117.449062  -4.245395   
306  53.936748  20.721496  29.220534  33.215251  114.365845  -0.421010   
307  61.446597  22.694968  46.170347  38.751628  125.670725  -2.707880   
308  45.252792   8.693157  41.583126  36.559635  118.545842   0.214750   
309  33.841641   5.073991  36.641233  28.767649  123.945244  -0.199249   

         Col7     Col8     Col9     Col10      Col11  
0    0.744503  12.5661  14.5386  15.30468 -28.658501  
1