In [8]:
from sklearn.utils import resample
import pandas as pd
import numpy as np

data = pd.read_csv('btissue(1).csv')
print("Data shape:", data.shape)

X = data.iloc[:, 0:9]
print("X shape:", X.shape)

# Resample with replacement (default)
X1 = resample(X, n_samples=200, random_state=0, replace=True)
print(X1.head(25))


Data shape: (106, 10)
X shape: (106, 9)
              I0     PA500       HFS           DA           Area        A/DA  \
44    172.515797  0.127235  0.038397    37.543673     192.218148    5.119855   
47    370.395725  0.104720  0.000000   115.923253    1308.120430   11.284366   
64    391.000000  0.058119  0.011170    35.780061     265.149790    7.410546   
67    145.000000  0.117635  0.110305    21.218942      82.455562    3.885941   
67    145.000000  0.117635  0.110305    21.218942      82.455562    3.885941   
103  1600.000000  0.071908 -0.066323   436.943603   12655.342130   28.963331   
9     423.000000  0.219562  0.261799   172.371241    6108.106297   35.435762   
83   1535.850740  0.088488  0.004189   637.349674   10814.050170   16.967217   
21    211.000000  0.053931  0.094248    30.753443     151.984578    4.942034   
36    178.000000  0.170868  0.212930    41.542167     489.440520   11.781776   
87   1666.148786  0.012392  0.058451    72.931050    1402.231665   19.226813   


In [11]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

predictors = data.iloc[:, 0:9]
target = data.iloc[:, 9]

predictors_train, predictors_test, target_train, target_test = train_test_split(
    predictors, target, test_size=0.25, random_state=42
)

print(predictors_train.head())


             I0     PA500       HFS          DA          Area        A/DA  \
73   649.369397  0.107512  0.018850  207.111691   3344.432678   16.147967   
15   390.000000  0.358316  0.203854  245.686103  10055.836870   40.929612   
77   691.972031  0.026005  0.086568  190.676692    304.270718    1.595742   
36   178.000000  0.170868  0.212930   41.542167    489.440520   11.781776   
88  1700.000000  0.043982  0.105127  120.653010  12331.103090  102.203029   

        Max IP          DR            P  
73   50.547470  200.848714   623.908814  
15   70.324783  236.490170   477.548360  
77   23.975718  189.163331   594.315626  
36   35.747795   21.162393   215.905934  
88  120.297318   -9.257696  2212.178196  


In [17]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split

# Prepare data
predictors = data.iloc[:, 0:9]
target = data.iloc[:, 9]

# Split data
predictors_train, predictors_test, target_train, target_test = train_test_split(
    predictors, target, test_size=0.25, random_state=42
)

# Train model
model = DecisionTreeClassifier(random_state=42)
model.fit(predictors_train, target_train)

# Predict on test set
prediction = model.predict(predictors_test)

# Calculate accuracy
acc = accuracy_score(target_test, prediction)
print("Accuracy:", acc)

# Confusion matrix
cm = confusion_matrix(target_test, prediction)
print("Confusion Matrix:\n", cm)


Accuracy: 0.7037037037037037
Confusion Matrix:
 [[3 0 0 0 0 0]
 [0 6 0 0 0 0]
 [0 0 4 0 0 0]
 [0 0 0 2 0 3]
 [0 0 0 1 2 2]
 [0 0 0 0 2 2]]


In [ ]:
# Fix: target should be last column, not all except last