In [1]:
import numpy as np

arr_1D= np.arange(12)
print(arr_1D)
index=[1,3,5]
print(index)
print(arr_1D[index])

#makin a mask function
mask= arr_1D%2==0
print(mask)
print(arr_1D[mask])

a2=arr_1D.copy()
print(a2)
print(a2%2==0)
a2[a2%2==0]=-1
print(a2)
# arr_2D= np.arange(arr_1D[index])


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[1, 3, 5]
[1 3 5]
[ True False  True False  True False  True False  True False  True False]
[ 0  2  4  6  8 10]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ True False  True False  True False  True False  True False  True False]
[-1  1 -1  3 -1  5 -1  7 -1  9 -1 11]


In [6]:
#Inverse of array'

import numpy as np

a1 = [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]
array_from_list = np.array(a1)
print(array_from_list)    

print(np.linalg.inv(a1))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [10]:
# a3D= np.zeros((2,3,3))
# print(a3D)
a4= np.random.randint(1,10,10).reshape(2, 5, 1)
print(a4)

[[[3]
  [5]
  [2]
  [5]
  [4]]

 [[6]
  [1]
  [5]
  [1]
  [7]]]
