In [1]:
import numpy as np
arr= np.array([10,20,30])
arr1= np.zeros(arr)
arr2=np.zeros([2,3,4])
print(arr2)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [6]:
import numpy as np
arr= np.array([10,20,30])
arr=np.arange(12).reshape(4,3)
# arr=np.linspace(0,3,5)
print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [7]:
#ones
arr3= np.ones((4,3))
print(arr3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
# Eye matrix
arr4= np.eye(3,2)
arr4a= np.eye(3,4)

print(arr4a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [20]:
#Type Conversion 
arr5=np.arange(1,6)
arr5a=arr5.astype(np.float32)
print(arr5a)

[1. 2. 3. 4. 5.]


In [30]:
#Slicing and Indexing
# arr=np.arange(0,90,10).reshape(3,3)
arr=np.arange(0,9)
print(arr[2:5])
print(arr[2:5:2]) #skiping
print(arr[2:-5])

[2 3 4]
[2 4]
[2 3]


In [45]:
#for 3D
arr3D=np.arange(32).reshape(2,4,4)
print(arr3D)
print(arr3D[0:1, 0:1, 0:1])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]
[[[0]]]


In [51]:
#Boolean Indexing
arr=np.arange(9)
indices=[1,2,3]
print(arr[indices])

#Copy after creating mask
mask= arr%2 ==0
print(arr[mask])
arr2=arr.copy()
arr2[arr2%2==0]=-100
print(arr2)

[1 2 3]
[0 2 4 6 8]
[-100    1 -100    3 -100    5 -100    7 -100]


In [65]:
#Common functions (UFuncs)
arr=np.arange(1,10).reshape(3,3)
print(arr)
arr1=np.sqrt(arr)
print(arr1)
arr2=np.sum(arr)
print(arr2)
arr3=np.sum(arr, axis=1)
print("Sum of rows ",arr3)
arr4= np.mean(arr)
print("Mean of array : ",arr4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
45
Sum of rows  [ 6 15 24]
Mean of array :  5.0


In [69]:
arr5=np.cumsum(arr)
print("Cumsum\n",arr5)

Cumsum
 [ 1  3  6 10 15 21 28 36 45]


In [72]:
# Linear Algebra
arr= np.arange(1,11).reshape(10,1)
arrr1=np.arange(1,10)
print("2D arr :", arr)
print("1D arr :", arr1)

#x=np.linalg.solve(arr, arr1)
print(arr1.dot(arr1))

2D arr : [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
1D arr : [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
[[ 8.41100282  9.47547071 10.39230485]
 [12.95287665 14.75663036 16.28979642]
 [16.23985949 18.55149408 20.51077893]]


In [88]:
import numpy as np

# Create a random number generator instance
arr = np.random.default_rng(50)

random_arr = arr.random((2, 3))
print(random_arr)


[[0.78742269 0.83366933 0.54790446]
 [0.9734491  0.23683356 0.64692334]]
